
package gov.va.med.esr.webservices.jaxws.schemas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "eeSummaryPortService", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", wsdlLocation = "file:/C:/Users/JoshuaHulbert/IdeaProjects/urgentcare-apis-parent/ee-artifacts/src/main/wsdl/eeSummary.wsdl")
public class EeSummaryPortService
    extends Service
{

    private final static URL EESUMMARYPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EESUMMARYPORTSERVICE_EXCEPTION;
    private final static QName EESUMMARYPORTSERVICE_QNAME = new QName("http://jaxws.webservices.esr.med.va.gov/schemas", "eeSummaryPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/JoshuaHulbert/IdeaProjects/urgentcare-apis-parent/ee-artifacts/src/main/wsdl/eeSummary.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EESUMMARYPORTSERVICE_WSDL_LOCATION = url;
        EESUMMARYPORTSERVICE_EXCEPTION = e;
    }

    public EeSummaryPortService() {
        super(__getWsdlLocation(), EESUMMARYPORTSERVICE_QNAME);
    }

    public EeSummaryPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EESUMMARYPORTSERVICE_QNAME, features);
    }

    public EeSummaryPortService(URL wsdlLocation) {
        super(wsdlLocation, EESUMMARYPORTSERVICE_QNAME);
    }

    public EeSummaryPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EESUMMARYPORTSERVICE_QNAME, features);
    }

    public EeSummaryPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EeSummaryPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EeSummaryPort
     */
    @WebEndpoint(name = "eeSummaryPortSoap11")
    public EeSummaryPort getEeSummaryPortSoap11() {
        return super.getPort(new QName("http://jaxws.webservices.esr.med.va.gov/schemas", "eeSummaryPortSoap11"), EeSummaryPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EeSummaryPort
     */
    @WebEndpoint(name = "eeSummaryPortSoap11")
    public EeSummaryPort getEeSummaryPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.webservices.esr.med.va.gov/schemas", "eeSummaryPortSoap11"), EeSummaryPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EESUMMARYPORTSERVICE_EXCEPTION!= null) {
            throw EESUMMARYPORTSERVICE_EXCEPTION;
        }
        return EESUMMARYPORTSERVICE_WSDL_LOCATION;
    }

}
