
package gov.va.med.esr.webservices.jaxws.schemas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "eeSummaryPort", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EeSummaryPort {


    /**
     * 
     * @param getEESummaryRequest
     * @return
     *     returns gov.va.med.esr.webservices.jaxws.schemas.GetEESummaryResponse
     */
    @WebMethod
    @WebResult(name = "getEESummaryResponse", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "getEESummaryResponse")
    public GetEESummaryResponse getEESummary(
        @WebParam(name = "getEESummaryRequest", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "getEESummaryRequest")
        GetEESummaryRequest getEESummaryRequest);

    /**
     * 
     * @param getEESummaryHistoryRequest
     * @return
     *     returns gov.va.med.esr.webservices.jaxws.schemas.GetEESummaryHistoryResponse
     */
    @WebMethod
    @WebResult(name = "getEESummaryHistoryResponse", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "getEESummaryHistoryResponse")
    public GetEESummaryHistoryResponse getEESummaryHistory(
        @WebParam(name = "getEESummaryHistoryRequest", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "getEESummaryHistoryRequest")
        GetEESummaryHistoryRequest getEESummaryHistoryRequest);

    /**
     * 
     * @param getEligibilityDeterminationRequest
     * @return
     *     returns gov.va.med.esr.webservices.jaxws.schemas.GetEligibilityDeterminationResponse
     */
    @WebMethod
    @WebResult(name = "getEligibilityDeterminationResponse", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "getEligibilityDeterminationResponse")
    public GetEligibilityDeterminationResponse getEligibilityDetermination(
        @WebParam(name = "getEligibilityDeterminationRequest", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "getEligibilityDeterminationRequest")
        GetEligibilityDeterminationRequest getEligibilityDeterminationRequest);

    /**
     * 
     * @param getPersonNotificationRequest
     * @return
     *     returns gov.va.med.esr.webservices.jaxws.schemas.GetPersonNotificationResponse
     */
    @WebMethod
    @WebResult(name = "getPersonNotificationResponse", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "getPersonNotificationResponse")
    public GetPersonNotificationResponse getPersonNotification(
        @WebParam(name = "getPersonNotificationRequest", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "getPersonNotificationRequest")
        GetPersonNotificationRequest getPersonNotificationRequest);

    /**
     * 
     * @param getDeliveryPreferenceRequest
     * @return
     *     returns gov.va.med.esr.webservices.jaxws.schemas.GetDeliveryPreferenceResponse
     */
    @WebMethod
    @WebResult(name = "getDeliveryPreferenceResponse", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "getDeliveryPreferenceResponse")
    public GetDeliveryPreferenceResponse getDeliveryPreference(
        @WebParam(name = "getDeliveryPreferenceRequest", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "getDeliveryPreferenceRequest")
        GetDeliveryPreferenceRequest getDeliveryPreferenceRequest);

    /**
     * 
     * @param updateDeliveryPreferenceRequest
     * @return
     *     returns gov.va.med.esr.webservices.jaxws.schemas.UpdateDeliveryPreferenceResponse
     */
    @WebMethod
    @WebResult(name = "updateDeliveryPreferenceResponse", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "updateDeliveryPreferenceResponse")
    public UpdateDeliveryPreferenceResponse updateDeliveryPreference(
        @WebParam(name = "updateDeliveryPreferenceRequest", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "updateDeliveryPreferenceRequest")
        UpdateDeliveryPreferenceRequest updateDeliveryPreferenceRequest);

    /**
     * 
     * @param retrieveIVMCandidatesRequest
     * @return
     *     returns gov.va.med.esr.webservices.jaxws.schemas.RetrieveIVMCandidatesResponse
     */
    @WebMethod
    @WebResult(name = "retrieveIVMCandidatesResponse", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "retrieveIVMCandidatesResponse")
    public RetrieveIVMCandidatesResponse retrieveIVMCandidates(
        @WebParam(name = "retrieveIVMCandidatesRequest", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "retrieveIVMCandidatesRequest")
        RetrieveIVMCandidatesRequest retrieveIVMCandidatesRequest);

    /**
     * 
     * @param getIVMLetterStatusesRequest
     * @return
     *     returns gov.va.med.esr.webservices.jaxws.schemas.GetIVMLetterStatusesResponse
     */
    @WebMethod
    @WebResult(name = "getIVMLetterStatusesResponse", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "getIVMLetterStatusesResponse")
    public GetIVMLetterStatusesResponse getIVMLetterStatuses(
        @WebParam(name = "getIVMLetterStatusesRequest", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "getIVMLetterStatusesRequest")
        GetIVMLetterStatusesRequest getIVMLetterStatusesRequest);

    /**
     * 
     * @param updateIVMRecordStatusRequest
     * @return
     *     returns gov.va.med.esr.webservices.jaxws.schemas.UpdateIVMRecordStatusResponse
     */
    @WebMethod
    @WebResult(name = "updateIVMRecordStatusResponse", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "updateIVMRecordStatusResponse")
    public UpdateIVMRecordStatusResponse updateIVMRecordStatus(
        @WebParam(name = "updateIVMRecordStatusRequest", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "updateIVMRecordStatusRequest")
        UpdateIVMRecordStatusRequest updateIVMRecordStatusRequest);

    /**
     * 
     * @param sendIVMUpdatesRequest
     * @return
     *     returns gov.va.med.esr.webservices.jaxws.schemas.SendIVMUpdatesResponse
     */
    @WebMethod
    @WebResult(name = "sendIVMUpdatesResponse", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "sendIVMUpdatesResponse")
    public SendIVMUpdatesResponse sendIVMUpdates(
        @WebParam(name = "sendIVMUpdatesRequest", targetNamespace = "http://jaxws.webservices.esr.med.va.gov/schemas", partName = "sendIVMUpdatesRequest")
        SendIVMUpdatesRequest sendIVMUpdatesRequest);

}
